            - name: Android Emulator Fleet
  # You may pin to the exact commit or the version.
  # uses: limbario/android-emulator-fleet@67ec841dc2409922b19f610b8358d558fbf5da8b
  uses: limbario/android-emulator-fleet@v0.4.7
  with:
    # Organization that the Android instance will belong to. If not given, the default organization from the token is used.
    organization-id: # optional
    # Region of the Android instance. The closest one is chosen if not given.
    region: # optional
    # Token to access Limbar.
    token: 
    # Number of Android instances to run.
    count: # optional, default is 1
                      - name: Setup Java JDK
  uses: actions/setup-java@v4.7.0
  with:
    # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
    java-version: # optional
    # The path to the `.java-version` file. See examples of supported syntax in README file
    java-version-file: # optional
    # Java distribution. See the list of supported distributions in README file
    distribution: 
    # The package type (jdk, jre, jdk+fx, jre+fx)
    java-package: # optional, default is jdk
    # The architecture of the package (defaults to the action runner's architecture)
    architecture: # optional
    # Path to where the compressed JDK is located
    jdkFile: # optional
    # Set this option if you want the action to check for the latest available version that satisfies the version spec
    check-latest: # optional
    # ID of the distributionManagement repository in the pom.xml file. Default is `github`
    server-id: # optional, default is github
    # Environment variable name for the username for authentication to the Apache Maven repository. Default is $GITHUB_ACTOR
    server-username: # optional, default is GITHUB_ACTOR
    # Environment variable name for password or token for authentication to the Apache Maven repository. Default is $GITHUB_TOKEN
    server-password: # optional, default is GITHUB_TOKEN
    # Path to where the settings.xml file will be written. Default is ~/.m2.
    settings-path: # optional
    # Overwrite the settings.xml file if it exists. Default is "true".
    overwrite-settings: # optional, default is true
    # GPG private key to import. Default is empty string.
    gpg-private-key: # optional
    # Environment variable name for the GPG private key passphrase. Default is $GPG_PASSPHRASE.
    gpg-passphrase: # optional
    # Name of the build platform to cache dependencies. It can be "maven", "gradle" or "sbt".
    cache: # optional
    # The path to a dependency file: pom.xml, build.gradle, build.sbt, etc. This option can be used with the `cache` option. If this option is omitted, the action searches for the dependency file in the entire repository. This option supports wildcards and a list of file names for caching multiple dependencies.
    cache-dependency-path: # optional
    # Workaround to pass job status to post job step. This variable is not intended for manual setting
    job-status: # optional, default is ${{ job.status }}
    # The token used to authenticate when fetching version manifests hosted on github.com, such as for the Microsoft Build of OpenJDK. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Name of Maven Toolchain ID if the default name of "${distribution}_${java-version}" is not wanted. See examples of supported syntax in Advanced Usage file
    mvn-toolchain-id: # optional
    # Name of Maven Toolchain Vendor if the default name of "${distribution}" is not wanted. See examples of supported syntax in Advanced Usage file
    mvn-toolchain-vendor: # optional
                      - name: Setup Go environment
  uses: actions/setup-go@v5.4.0
  with:
    # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
    go-version: # optional
    # Path to the go.mod or go.work file.
    go-version-file: # optional
    # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
    check-latest: # optional
    # Used to pull Go distributions from go-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
    cache: # optional, default is true
    # Used to specify the path to a dependency file - go.sum
    cache-dependency-path: # optional
    # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
    architecture: # optional
                      - name: First interaction
  uses: actions/first-interaction@v1.3.0
  with:
    # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
    repo-token: 
    # Comment to post on an individual's first issue
    issue-message: # optional
    # Comment to post on an individual's first pull request
    pr-message: # optional
                      - name: Android Emulator Fleet
  # You may pin to the exact commit or the version.
  # uses: limbario/android-emulator-fleet@67ec841dc2409922b19f610b8358d558fbf5da8b
  uses: limbario/android-emulator-fleet@v0.4.7
  with:
    # Organization that the Android instance will belong to. If not given, the default organization from the token is used.
    organization-id: # optional
    # Region of the Android instance. The closest one is chosen if not given.
    region: # optional
    # Token to access Limbar.
    token: 
    # Number of Android instances to run.
    count: # optional, default is 1
                      - name: Publish Android
  # You may pin to the exact commit or the version.
  # uses: joutvhu/publish-android@58c5064befa747851fc826c523a26d158eae50df
  uses: joutvhu/publish-android@v1.0.1
  with:
    # The service account json private key file or the raw json text of the service account private key to authorize the upload request
    serviceAccountJson: 
    # The package name, or Application Id, of the app you are uploading
    packageName: 
    # The Android release file to upload (.apk or .aab). Multiple files can be supplied on new lines. Supports glob
    releaseFile: 
    # The name of this release. If not set it's generated automatically from the APKs versionName. Default is configured by Google Play Console
    releaseName: # optional
    # The track in which you want to assign the uploaded app.
    track: # default is production
    # In-app update priority of the release. All newly added APKs in the release will be considered at this priority. Can take values in the range [0, 5], with 5 the highest priority.
    inAppUpdatePriority: # optional, default is 0
    # Portion of users who should get the staged version of the app. Accepts values between 0.0 and 1.0 (exclusive-exclusive).
    userFraction: # optional
    # Release status. This can be set to 'draft' to complete the release at some other time.
    status: # optional, default is completed
    # The directory of localized "whats new" files to upload as the release notes. The files contained in the whatsNewDirectory MUST use the pattern whatsnew-<LOCALE> where LOCALE is using the BCP 47 format
    whatsNewDirectory: # optional
    # The mapping.txt file used to de-obfuscate your stack traces from crash reports
    mappingFile: # optional
    # The native-debug-symbols.zip file or folder that contains your debug symbols
    debugSymbols: # optional
    # Indicates that the changes in this edit will not be reviewed until they are explicitly sent for review from the Google Play Console
    changesNotSentForReview: # optional, default is false
    # The ID of an existing edit that has not been completed. If this is supplied, the action will append information to that rather than creating an edit
    existingEditId: # optional
                      - name: Android Builder
  # You may pin to the exact commit or the version.
  # uses: b4s36t4/Android-Action@bb5c066db6ca0824ee09ee640ca222888a0c2877
  uses: b4s36t4/Android-Action@0.0.1
                      - name: Gradle Android
  # You may pin to the exact commit or the version.
  # uses: Raul6469/android-gradle-action@b8fc7c7bde2562a4578b7e1bd996cc78d841638e
  uses: Raul6469/android-gradle-action@2.0.0
  with:
    # The ./gradlew command arguments
    script: 
    # Your Android license agreement id
    android-licence: # optional
                      - name: Apksigner Android
  # You may pin to the exact commit or the version.
  # uses: upup-company/apksigner-android@d4a55a2f7bb2541fe6d2c08287c3f4222a7c9b52
  uses: upup-company/apksigner-android@v1
  with:
    # The directory to find your release to sign
    releaseDirectory: 
    # The key used to sign your release in base64 encoded format
    signingKeyBase64: 
    # The key alias
    alias:             - name: Android Build
  # You may pin to the exact commit or the version.
  # uses: vgaidarji/android-github-actions-build@0888eff41ad409a802aa4ccd7790a91891da9056
  uses: vgaidarji/android-github-actions-build@v1.0.1
          
    # The password to the keystore
    keyStorePassword: 
    # The password for the key
    keyPassword: # optional
    # The custom args passed to apksigner
    customArgs: # optional
                      - name: Deltadox-Android
  # You may pin to the exact commit or the version.
  # uses: deltadox/deltadox-android@c30cccad8817b5c3b1fc2bfabf8e7779d779c182
  uses: deltadox/deltadox-android@1.2.0
  with:
    # Input to use
    myInput: # optional, default is world
                      - name: Setup Android SDK Tools
  # You may pin to the exact commit or the version.
  # uses: android-actions/setup-android@00854ea68c109d98c75d956347303bf7c45b0277
  uses: android-actions/setup-android@v3.2.1
  with:
    # cmdline-tools-version. See https://developer.android.com/studio#command-line-tools-only
    cmdline-tools-version: # optional, default is 10406996
    # Android SDK is usable only after the license agreement. Should setup-android agree to the licences, provided by "sdkmanager --licenses"
    accept-android-sdk-licenses: # optional, default is true
    # Should accepted licenses be logged. If not, accepted licences will be accepted silently
    log-accepted-android-sdk-licenses: # optional, default is true
    # Additional packages to install
    packages: # optional, default is tools platform-tools
          
